spring:
  application:
    name: dppservice

  kafka:
    bootstrap-servers: 172.16.1.105:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"admin\" password=\"admin-secret\";"

      ssl:
        truststore:
          location: /usr/local/kafka.truststore.jks
          password: truststore-password
          type: JKS
        endpoint-identification-algorithm: https

coding:
  practitionnerCategory:
    system: "CNSS"
    validation: "optional"
  practitionnerSpeciality:
    system: "CNSS"
    validation: "optional"
  encounterClass:
    system: "http://snomed.info/sct"
    validation: "required"


app:
  kafka:
    topic:
      declarationssih: "declarationssih"
  validation:
    # Set to true to validate the bundle structure and profiles
    bundle-enabled: true
    # Set to true to validate terminology and coding systems (requires internet or local terminology server)
    coding-enabled: true
    

    
# Logging levels (uncomment as needed)
#logging:
#  level:
#    org.springframework.kafka: DEBUG
#    org.apache.kafka: DEBUG
#    sun.security.ssl: DEBUG
#    org.apache.kafka.common.network: DEBUG