version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres  # Optional: explicitly set database name
    volumes:
      - c:\docker\pgtest:/var/lib/postgresql
    # Optional: add restart policy
    restart: unless-stopped

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    #environment:
      # Only 3 essential parameters for KRaft mode
      #KAFKA_NODE_ID: 1
      #KAFKA_PROCESS_ROLES: controller,broker
      #KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
	  #KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"  # <-- ADD THIS LINE
    # The image has sensible defaults for other parameters

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092